// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package ir.tourismit.tit.core;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ir.tourismit.tit.core.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ProcessID = 1;</code>
   */
  java.lang.String getProcessID();
  /**
   * <code>string ProcessID = 1;</code>
   */
  com.google.protobuf.ByteString
      getProcessIDBytes();

  /**
   * <code>string ProcessReference = 2;</code>
   */
  java.lang.String getProcessReference();
  /**
   * <code>string ProcessReference = 2;</code>
   */
  com.google.protobuf.ByteString
      getProcessReferenceBytes();

  /**
   * <code>string CallerReference = 3;</code>
   */
  java.lang.String getCallerReference();
  /**
   * <code>string CallerReference = 3;</code>
   */
  com.google.protobuf.ByteString
      getCallerReferenceBytes();

  /**
   * <code>string ServiceID = 4;</code>
   */
  java.lang.String getServiceID();
  /**
   * <code>string ServiceID = 4;</code>
   */
  com.google.protobuf.ByteString
      getServiceIDBytes();

  /**
   * <code>string CallerInputJson = 5;</code>
   */
  java.lang.String getCallerInputJson();
  /**
   * <code>string CallerInputJson = 5;</code>
   */
  com.google.protobuf.ByteString
      getCallerInputJsonBytes();

  /**
   * <code>string PreviewsOutput = 6;</code>
   */
  java.lang.String getPreviewsOutput();
  /**
   * <code>string PreviewsOutput = 6;</code>
   */
  com.google.protobuf.ByteString
      getPreviewsOutputBytes();

  /**
   * <code>string TokenAA = 7;</code>
   */
  java.lang.String getTokenAA();
  /**
   * <code>string TokenAA = 7;</code>
   */
  com.google.protobuf.ByteString
      getTokenAABytes();
}
