// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package ir.tourismit.tit.core;

/**
 * Protobuf type {@code ir.tourismit.tit.core.Response}
 */
public  final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ir.tourismit.tit.core.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    processReference_ = "";
    outputJson_ = "";
    responseCode_ = "";
    responseDescription_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            processReference_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            outputJson_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            responseCode_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            responseDescription_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ir.tourismit.tit.core.ServiceOuterClass.internal_static_ir_tourismit_tit_core_Response_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ir.tourismit.tit.core.ServiceOuterClass.internal_static_ir_tourismit_tit_core_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ir.tourismit.tit.core.Response.class, ir.tourismit.tit.core.Response.Builder.class);
  }

  public static final int PROCESSREFERENCE_FIELD_NUMBER = 1;
  private volatile java.lang.Object processReference_;
  /**
   * <code>string ProcessReference = 1;</code>
   */
  public java.lang.String getProcessReference() {
    java.lang.Object ref = processReference_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processReference_ = s;
      return s;
    }
  }
  /**
   * <code>string ProcessReference = 1;</code>
   */
  public com.google.protobuf.ByteString
      getProcessReferenceBytes() {
    java.lang.Object ref = processReference_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processReference_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OUTPUTJSON_FIELD_NUMBER = 2;
  private volatile java.lang.Object outputJson_;
  /**
   * <code>string OutputJson = 2;</code>
   */
  public java.lang.String getOutputJson() {
    java.lang.Object ref = outputJson_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      outputJson_ = s;
      return s;
    }
  }
  /**
   * <code>string OutputJson = 2;</code>
   */
  public com.google.protobuf.ByteString
      getOutputJsonBytes() {
    java.lang.Object ref = outputJson_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      outputJson_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSECODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object responseCode_;
  /**
   * <code>string ResponseCode = 3;</code>
   */
  public java.lang.String getResponseCode() {
    java.lang.Object ref = responseCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responseCode_ = s;
      return s;
    }
  }
  /**
   * <code>string ResponseCode = 3;</code>
   */
  public com.google.protobuf.ByteString
      getResponseCodeBytes() {
    java.lang.Object ref = responseCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responseCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSEDESCRIPTION_FIELD_NUMBER = 4;
  private volatile java.lang.Object responseDescription_;
  /**
   * <code>string ResponseDescription = 4;</code>
   */
  public java.lang.String getResponseDescription() {
    java.lang.Object ref = responseDescription_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      responseDescription_ = s;
      return s;
    }
  }
  /**
   * <code>string ResponseDescription = 4;</code>
   */
  public com.google.protobuf.ByteString
      getResponseDescriptionBytes() {
    java.lang.Object ref = responseDescription_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      responseDescription_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getProcessReferenceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, processReference_);
    }
    if (!getOutputJsonBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, outputJson_);
    }
    if (!getResponseCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, responseCode_);
    }
    if (!getResponseDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, responseDescription_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getProcessReferenceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, processReference_);
    }
    if (!getOutputJsonBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, outputJson_);
    }
    if (!getResponseCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, responseCode_);
    }
    if (!getResponseDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, responseDescription_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ir.tourismit.tit.core.Response)) {
      return super.equals(obj);
    }
    ir.tourismit.tit.core.Response other = (ir.tourismit.tit.core.Response) obj;

    boolean result = true;
    result = result && getProcessReference()
        .equals(other.getProcessReference());
    result = result && getOutputJson()
        .equals(other.getOutputJson());
    result = result && getResponseCode()
        .equals(other.getResponseCode());
    result = result && getResponseDescription()
        .equals(other.getResponseDescription());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROCESSREFERENCE_FIELD_NUMBER;
    hash = (53 * hash) + getProcessReference().hashCode();
    hash = (37 * hash) + OUTPUTJSON_FIELD_NUMBER;
    hash = (53 * hash) + getOutputJson().hashCode();
    hash = (37 * hash) + RESPONSECODE_FIELD_NUMBER;
    hash = (53 * hash) + getResponseCode().hashCode();
    hash = (37 * hash) + RESPONSEDESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getResponseDescription().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ir.tourismit.tit.core.Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.tourismit.tit.core.Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.tourismit.tit.core.Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.tourismit.tit.core.Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.tourismit.tit.core.Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ir.tourismit.tit.core.Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ir.tourismit.tit.core.Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ir.tourismit.tit.core.Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ir.tourismit.tit.core.Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ir.tourismit.tit.core.Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ir.tourismit.tit.core.Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ir.tourismit.tit.core.Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ir.tourismit.tit.core.Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ir.tourismit.tit.core.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ir.tourismit.tit.core.Response)
      ir.tourismit.tit.core.ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ir.tourismit.tit.core.ServiceOuterClass.internal_static_ir_tourismit_tit_core_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ir.tourismit.tit.core.ServiceOuterClass.internal_static_ir_tourismit_tit_core_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ir.tourismit.tit.core.Response.class, ir.tourismit.tit.core.Response.Builder.class);
    }

    // Construct using ir.tourismit.tit.core.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      processReference_ = "";

      outputJson_ = "";

      responseCode_ = "";

      responseDescription_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ir.tourismit.tit.core.ServiceOuterClass.internal_static_ir_tourismit_tit_core_Response_descriptor;
    }

    @java.lang.Override
    public ir.tourismit.tit.core.Response getDefaultInstanceForType() {
      return ir.tourismit.tit.core.Response.getDefaultInstance();
    }

    @java.lang.Override
    public ir.tourismit.tit.core.Response build() {
      ir.tourismit.tit.core.Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ir.tourismit.tit.core.Response buildPartial() {
      ir.tourismit.tit.core.Response result = new ir.tourismit.tit.core.Response(this);
      result.processReference_ = processReference_;
      result.outputJson_ = outputJson_;
      result.responseCode_ = responseCode_;
      result.responseDescription_ = responseDescription_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ir.tourismit.tit.core.Response) {
        return mergeFrom((ir.tourismit.tit.core.Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ir.tourismit.tit.core.Response other) {
      if (other == ir.tourismit.tit.core.Response.getDefaultInstance()) return this;
      if (!other.getProcessReference().isEmpty()) {
        processReference_ = other.processReference_;
        onChanged();
      }
      if (!other.getOutputJson().isEmpty()) {
        outputJson_ = other.outputJson_;
        onChanged();
      }
      if (!other.getResponseCode().isEmpty()) {
        responseCode_ = other.responseCode_;
        onChanged();
      }
      if (!other.getResponseDescription().isEmpty()) {
        responseDescription_ = other.responseDescription_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ir.tourismit.tit.core.Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ir.tourismit.tit.core.Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object processReference_ = "";
    /**
     * <code>string ProcessReference = 1;</code>
     */
    public java.lang.String getProcessReference() {
      java.lang.Object ref = processReference_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processReference_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ProcessReference = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProcessReferenceBytes() {
      java.lang.Object ref = processReference_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processReference_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ProcessReference = 1;</code>
     */
    public Builder setProcessReference(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      processReference_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ProcessReference = 1;</code>
     */
    public Builder clearProcessReference() {
      
      processReference_ = getDefaultInstance().getProcessReference();
      onChanged();
      return this;
    }
    /**
     * <code>string ProcessReference = 1;</code>
     */
    public Builder setProcessReferenceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      processReference_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object outputJson_ = "";
    /**
     * <code>string OutputJson = 2;</code>
     */
    public java.lang.String getOutputJson() {
      java.lang.Object ref = outputJson_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        outputJson_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string OutputJson = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOutputJsonBytes() {
      java.lang.Object ref = outputJson_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        outputJson_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string OutputJson = 2;</code>
     */
    public Builder setOutputJson(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      outputJson_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string OutputJson = 2;</code>
     */
    public Builder clearOutputJson() {
      
      outputJson_ = getDefaultInstance().getOutputJson();
      onChanged();
      return this;
    }
    /**
     * <code>string OutputJson = 2;</code>
     */
    public Builder setOutputJsonBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      outputJson_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object responseCode_ = "";
    /**
     * <code>string ResponseCode = 3;</code>
     */
    public java.lang.String getResponseCode() {
      java.lang.Object ref = responseCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ResponseCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResponseCodeBytes() {
      java.lang.Object ref = responseCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ResponseCode = 3;</code>
     */
    public Builder setResponseCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      responseCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ResponseCode = 3;</code>
     */
    public Builder clearResponseCode() {
      
      responseCode_ = getDefaultInstance().getResponseCode();
      onChanged();
      return this;
    }
    /**
     * <code>string ResponseCode = 3;</code>
     */
    public Builder setResponseCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      responseCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object responseDescription_ = "";
    /**
     * <code>string ResponseDescription = 4;</code>
     */
    public java.lang.String getResponseDescription() {
      java.lang.Object ref = responseDescription_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseDescription_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ResponseDescription = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResponseDescriptionBytes() {
      java.lang.Object ref = responseDescription_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ResponseDescription = 4;</code>
     */
    public Builder setResponseDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      responseDescription_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ResponseDescription = 4;</code>
     */
    public Builder clearResponseDescription() {
      
      responseDescription_ = getDefaultInstance().getResponseDescription();
      onChanged();
      return this;
    }
    /**
     * <code>string ResponseDescription = 4;</code>
     */
    public Builder setResponseDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      responseDescription_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ir.tourismit.tit.core.Response)
  }

  // @@protoc_insertion_point(class_scope:ir.tourismit.tit.core.Response)
  private static final ir.tourismit.tit.core.Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ir.tourismit.tit.core.Response();
  }

  public static ir.tourismit.tit.core.Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    @java.lang.Override
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ir.tourismit.tit.core.Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

