// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package ir.tourismit.tit.core;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ir.tourismit.tit.core.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ProcessReference = 1;</code>
   */
  java.lang.String getProcessReference();
  /**
   * <code>string ProcessReference = 1;</code>
   */
  com.google.protobuf.ByteString
      getProcessReferenceBytes();

  /**
   * <code>string OutputJson = 2;</code>
   */
  java.lang.String getOutputJson();
  /**
   * <code>string OutputJson = 2;</code>
   */
  com.google.protobuf.ByteString
      getOutputJsonBytes();

  /**
   * <code>string ResponseCode = 3;</code>
   */
  java.lang.String getResponseCode();
  /**
   * <code>string ResponseCode = 3;</code>
   */
  com.google.protobuf.ByteString
      getResponseCodeBytes();

  /**
   * <code>string ResponseDescription = 4;</code>
   */
  java.lang.String getResponseDescription();
  /**
   * <code>string ResponseDescription = 4;</code>
   */
  com.google.protobuf.ByteString
      getResponseDescriptionBytes();
}
