// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package ir.tourismit.tit.core;

public final class ServiceOuterClass {
  private ServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ir_tourismit_tit_core_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ir_tourismit_tit_core_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ir_tourismit_tit_core_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ir_tourismit_tit_core_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rService.proto\022\025ir.tourismit.tit.core\"\244" +
      "\001\n\007Request\022\021\n\tProcessID\030\001 \001(\t\022\030\n\020Process" +
      "Reference\030\002 \001(\t\022\027\n\017CallerReference\030\003 \001(\t" +
      "\022\021\n\tServiceID\030\004 \001(\t\022\027\n\017CallerInputJson\030\005" +
      " \001(\t\022\026\n\016PreviewsOutput\030\006 \001(\t\022\017\n\007TokenAA\030" +
      "\007 \001(\t\"k\n\010Response\022\030\n\020ProcessReference\030\001 " +
      "\001(\t\022\022\n\nOutputJson\030\002 \001(\t\022\024\n\014ResponseCode\030" +
      "\003 \001(\t\022\033\n\023ResponseDescription\030\004 \001(\t2U\n\007Se" +
      "rvice\022J\n\007service\022\036.ir.tourismit.tit.core" +
      ".Request\032\037.ir.tourismit.tit.core.Respons" +
      "eB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ir_tourismit_tit_core_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ir_tourismit_tit_core_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ir_tourismit_tit_core_Request_descriptor,
        new java.lang.String[] { "ProcessID", "ProcessReference", "CallerReference", "ServiceID", "CallerInputJson", "PreviewsOutput", "TokenAA", });
    internal_static_ir_tourismit_tit_core_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ir_tourismit_tit_core_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ir_tourismit_tit_core_Response_descriptor,
        new java.lang.String[] { "ProcessReference", "OutputJson", "ResponseCode", "ResponseDescription", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
